### ISSUE TITLE
jar on Dockerhub image missing manifest file and/or extra jar in docker image

### ISSUE THREAD

**Issue by sleightsec** [hygieia/api-audit#87]
Affects: latest - multiple dockerhub images tested back to 3.5.14

When running the docker images: `docker run -t -e SKIP_PROPERTIES_BUILDER=true -v apiauditproperties:/hygieia/config -i -i hygieiadoc/apiaudit`

Receive the error: "no main manifest attribute, in api-audit-javadoc.jar"

Building the application from source and the docker image using the Dockerfile found in the repo, and the image runs correctly. In locally built image there is no api-audit-javadoc.jar nor api-audit-sources.jar both of which are in the Dockerhub images

Possible Solutions:

- Remove extra jars from docker image
- Modify Dockerfile "CMD" to only run the expected api-audit.jar instead of *.jar

**Comment by rvema** [comment]
@sleightsec please create a PR for addressing this fix and the change will be accepted
